### PR TITLE
Adding graphics resources maded by edeksumo

### PR DESCRIPTION
**Pull request by Illithidek**
Adding graphics for QuickRecruitmentWindow

### CODE REVIEW

**Review by alexvins — CHANGES_REQUESTED** [review]
Button icons are just a copy of original itmcl.def. Not acceptible.

**Comment by Illithidek** [comment]
@alexvins in itmcl.def you don't have animation for pressing. You have only static frames for none, fort, citadel and castle.

**Comment by alexvins** [comment]
It does not matter. frame 0 is a copy, frame 1 is derivative from frame 0.

**Comment by Illithidek** [comment]
Well ok, I will tell him to change a bit graphics.

**Comment by Illithidek** [comment]
bump

**Comment by alexvins** [comment]
Now it is a copy of `ircbtns.def`.

**Review by alexvins — APPROVED** [review]

**Pull request merged**
